### ISSUE TITLE
Maybe use square tiles in Pacman?

### ISSUE THREAD

**Issue by hackerb9** [forth2020/frenchie68#3]
This may be a bad idea, but I believe the VT420 can change the number of screen lines so that each character cell is a 10x10 square.  This might make animation look smoother. For example, if the ghosts were each a 20x20 square, cut into four pieces, you'd be able to move them by half-steps up and down.

The downside with square tiles would be that VT340 compatibility would be much harder, if not impossible, as the VT340 cannot change the number of lines on the screen.

_____
_Sidenote:_

The original Pac-Man arcade machine used 8x8 square tiles in a grid 28 wide and 36 tall according to the [Pacman Dossier](https://pacman.holenet.info/#Chapter_3). But that's not of much relevance since it had hardware sprites which were not necessarily aligned with the grid:

![TileMove2](https://github.com/forth2020/frenchie68/assets/10174223/dd0292c6-648a-4cd4-a32e-59adfd7a4b64)

**Comment by frenchie68** [comment]
Respect Hackerb9,

I did spend twelve days full time on custom font design for this project. It is meant to be VT420 specific from the get go.
Sprites are indeed conceived to be double width characters, each of which is a 10 columns by 16 rows full cell entity.
I will remain in the default VT420 operating mode, which is 80 columns by 24 lines.

I am aware of the "Pacman dossier" and it's very close to being my preferred bed time reading--just after Moliere's "Le Mysanthrope" or Blaise Pascal's "Les Pensees"!

**Comment by hackerb9** [comment]
Thank you for the politest "no" I have ever received. I respect your design decisions and hope to some day find a VT420 to run Forth Pacman.
___
P.S. I never not yet read _Le Mysanthrope_; I will check it out!
